
version: '3.5'

services:

  vehicle-hire:
    container_name: VehicleHire
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /root/Dropbox/vehiclehire-logs:/home/vehcile-hire-logs-folder
    environment:
      - "JVM_OPTIONS=-Delastic.apm.service_name=VehicleHire -Delastic.apm.application_packages=com.babcock -Delastic.apm.server_urls=http://apm-server:8200"
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - sVehicleHiredockerelk_elk
networks:
  sVehicleHiredockerelk_elk:
    external: true
