DROP TABLE IF EXISTS VEHICLE;

CREATE TABLE VEHICLE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  REGISTRATION_NUMBER VARCHAR(50) NOT NULL,
  CATEGORY VARCHAR(20) NOT NULL,
  MAKE VARCHAR(250) NOT NULL,
  MODEL VARCHAR(250) NOT NULL,
  FUEL_TYPE VARCHAR(10) NOT NULL,
  CUSTOMER VARCHAR(50),
  PRICE_PER_DAY NUMERIC NOT NULL,
  HIRE_START_DATE DATE,
  HIRE_END_DATE DATE
);

INSERT INTO
	VEHICLE (REGISTRATION_NUMBER, CATEGORY, MAKE, MODEL, FUEL_TYPE, CUSTOMER, PRICE_PER_DAY, HIRE_START_DATE, HIRE_END_DATE)
VALUES
  	('REG1', 'Estate car', 'Ford', 'Focus', 'Petrol', 'Sam', '35', '2020-08-01', '2020-11-07'),
  	('REG2', 'Small car', 'Mercedes', 'C class', 'Petrol', 'John', '50', null, null),
  	('REG3', 'Van', 'VW', 'Transporter', 'Diesel', 'Doe', '50', '2020-08-11', '2020-11-19');
